### ISSUE TITLE
Corregir opción de la primera pregunta

### ISSUE THREAD

**Issue by Hatsumyxd12** [DrakthinK/triviav2#1]
Se encontró la palabra copilado y era compilado
![image](https://user-images.githubusercontent.com/113637509/190501103-8177478b-ef78-48a0-bf99-9a499bd04bff.png)

**Comment by DrakthinK** [comment]
deacuerdo, ya se corrigio
![image](https://user-images.githubusercontent.com/49349431/190506216-01faee80-1fdd-4cdf-8a4f-170a0831ce6a.png)
